# Generated by Django 5.1.4 on 2025-04-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_troca_destinatario_troca_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troca',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='troca',
            name='solicitante',
        ),
    ]
