# Generated by Django 5.1.4 on 2025-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0003_remove_troca_destinatario_remove_troca_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='trocaguarda',
            name='tipo',
            field=models.CharField(choices=[('SB', 'Subtenente'), ('A', 'Atirador'), ('S', 'Sargento'), ('C', 'Cabo')], default=5, max_length=12),
            preserve_default=False,
        ),
    ]
