# Generated by Django 5.1.4 on 2025-05-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0004_trocaguarda_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trocaguarda',
            name='tipo',
        ),
    ]
